language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
before_install:
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  # - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - cd ./embark_demo
cache: npm
install:
  - npm install
script:
  - npm run test